export const REOPS_IS_LOADIND = 'REOPS_IS_LOADIND'
export const REOPS_LOAD_SUCCESS = 'REOPS_LOAD_SUCCESS'
export const REOPS_LOAD_FAIL = 'REOPS_LOAD_FAIL'

export const CLEAR_ERROR = 'REOPS_LOAD_FAIL'